#!/bin/bash

clear
echo "Vous n'avez pas configurer la variable : DSINRD"
echo "Dans la fichier de config de ResPinGuy dans la categorie make-initrd-distribtuion :"
echo "Lancer la commande : respinguy-config"
echo "Lire la documentation sur la configuration de initrd respinguy a l'adresse suivante :"
echo "http://respinguy.tk/page/plus/doc.html#initrd"
read -p "Appuyez sur une touche pour terminer ..."
cd /usr/share/ResPinGuy-File/fichier/initrd/
rm -r make-initrd
exit 1 && exit 1
