#!/bin/bash
#######################################################################
rm Install-ResPinGuy
# Root
allow_only_root()
{
  if [ "0$UID" -ne 0 ]; then
     echo "Merci d'être en root pour lancer L'installation"; exit 1
  fi
}
allow_only_root
clear
#######################################################################
# Vérification les dependences
wget respinguy.tk/ftp/file-respinguy/Ver-Dep-ResPinGuy && bash Ver-Dep-ResPinGuy
#######################################################################
# Téléchargement, deplacement, extraction, ...
wget http://respinguy.tk/ftp/file-respinguy/file-respinguy.zip
clear
read -p "Continuer ..."
mv file-respinguy.zip /tmp/
echo "... [1/5]"
cd /tmp/
echo "... [2/5]"
unzip file-respinguy.zip
echo "... [3/5]"
rm file-respinguy.zip
echo "... [4/5]"
cd /tmp/file-respinguy/
echo "... [5/5]"
#######################################################################
# Copie, ...
read -p "Continuer ..."
cp respinguy /usr/bin/
chmod +x /usr/bin/respinguy
echo "... [1/6]"
cp respinguy-app-rm /usr/bin/
chmod +x /usr/bin/respinguy-app-rm
echo "... [2/6]"
cp respinguy-app-up /usr/bin/
chmod +x /usr/bin/respinguy-app-up
echo "... [3/6]"
cp respinguy-build /usr/bin/
chmod +x /usr/bin/respinguy-build
echo "... [4/6]"
cp respinguy-config /usr/bin/
chmod +x /usr/bin/respinguy-config
echo "... [5/6]"
cp respinguy-app-dep /usr/bin/
chmod +x /usr/bin/respinguy-app-dep
echo "... [6/6]"
echo "Les commandes sont Installer."
#
cp -r ResPinGuy-File-Conf/ /usr/share/
echo "... [1/4]"
cp -r ResPinGuy-File/ /usr/share/
echo "... [2/4]"
cp -r respinguy-build-dir /
echo "... [3/4]"
rm -r /tmp/file-respinguy/
echo "... [4/4]"
echo "Les Fichiers sont Installer."
#
#################################
read -p "ResPinGuy est executable sur votre machine. Terminer."
clear
echo "---"
echo "Lancer la commande : respinguy"
echo "---"
#######################################################################